### ISSUE TITLE
Why are only two modes available

### ISSUE THREAD

**Issue by wrousseau** [mcfly-io/gulp-mux#56]
Hi there,

Not sure this is the right place to ask but I'm using gulp-mux within the mc-fly generator, and I've been wondering why we can only use the dev and prod modes ? I'm guessing it is by design but when working with more environments for a single target, what is your recommendation ? 

Thanks for the great work,

Cheers,

Woody

**Comment by thaiat** [comment]
Hi,

what other environments would you have for a single target ?

**Comment by wrousseau** [comment]
In my case, we have a staging environment on which we deploy features, a production environment on which lives the stable version of the application, and a pre-production which is similar to the production environment but on which we check everything before deploying to production.

**Comment by thaiat** [comment]
ok but the code is identical between pre prod and prod ?

**Comment by wrousseau** [comment]
No, I'm also using gulp-ng-constants to inject different environment variables as APIs are also available for each environment

**Comment by thaiat** [comment]
mmm i m not sure i understand, the only purpose of dev and prod in gulp-mux is too deal with minification of the code, and build the correct dist folder with the resulting files
you can dist to prod or to dev mutliple times, and use the dist folder to install your code on the relevant server.

As for the different variables, a better choice is to use envify and env variables that are set on the server instance:

```js
var api = {
   url : process.env.api_url
}
```

see what i mean ?

**Comment by wrousseau** [comment]
Basically, you are saying we should use the `prod` mode for each environment if we want minification, and that we should use another flag which is not built in gmux if we want to inject env variables and deploy on the appropriate servers ?

I probably did not explain this correctly but we do not use any server instance, we are simply deploying to private stores, and we need to inject in the angular application variables (such as API urls) which depend on the environment.

**Comment by thaiat** [comment]
yes exactly, envify will resolve the env variables for you
you can modify the following function `getEnvifyVars` in `gulp_tasks/common/helper.js`:

```js
var getEnvifyVars = function(constants) {
    var version = readJsonFile('./package.json').version;
    var dest = constants.dist.distFolder;
    dest = isMobile(constants) ? dest + '/www/' + constants.script.dest : dest + '/' + constants.script.dest;
    var mode = constants.mode;
    var target = constants.targetName;
    var bundleName = constants.bundleName || 'bundle.js';
    var releaseName = target + '-v' + version;
    var envifyVars = {
        APP_VERSION: version,
        SENTRY_CLIENT_KEY: constants.sentry.targetKeys[target],
        SENTRY_RELEASE_NAME: releaseName,
        SENTRY_MODE: mode,
        SENTRY_NORMALIZED_URL: resolveSentryNormalizedUrl(constants),
        SENTRY_BUNDLE_NAME: bundleName,
        TARGET: target,
        PROTRACTOR: process.env.PROTRACTOR
    };
    if (isMobile(constants)) {
        var srcxml = './' + constants.clientFolder + '/config' + constants.targetSuffix + '.xml';
        var configFileContent = readTextFile(srcxml);
        var xml = new XML(configFileContent);
        envifyVars.APP_NAME = xml.child('name').getValue();
        envifyVars.APP_ID = xml.attribute('id').getValue();
        envifyVars.APP_AUTHOR = xml.child('author').getValue();
        envifyVars.TESTFAIRY_IOS_APP_TOKEN = constants.testfairy.ios_app_token;
        if (constants.ionic[target]) {
            envifyVars.IONIC_APP_ID = constants.ionic[target].app_id;
            envifyVars.IONIC_API_KEY = constants.ionic[target].api_key;
        }

    } else {
        envifyVars.APP_NAME = constants.appname;
    }
    return envifyVars;
};
```

Let me know if this makes sense

**Comment by wrousseau** [comment]
It does make sense, I'll be trying something along these lines ! I'll keep you posted :) Thanks a lot

**Comment by thaiat** [comment]
closing this for now, feel free to reopen if needed
